<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <AssemblyName>RAMFlow</AssemblyName>
    <RootNamespace>RAMFlow</RootNamespace>
    <Version>1.0.0</Version>
    <Product>RAM Flow</Product>
    <Description>Очистка оперативной памяти Windows</Description>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

</Project>
